### ISSUE TITLE
Subsequent file writes in the same process result in no data being written

### ISSUE THREAD

**Issue by cschenck** [alephzero/py#25]
I've been using `a0.File` to write to files on disk as a way of moving logs around. However, I noticed in my scripts that if I try to write to more than one file in the same process, all files except the first aren't written to. Here's an example that reproduces the issue:
```
def test_fn():
    fp = "/tmp/test.log"
    i = 0
    while os.path.exists(fp):
        fp = f"/tmp/test{i}.log"
        i += 1
    a0_file_options = a0.File.Options.DEFAULT
    a0_file = a0.File(fp, a0_file_options)
    pub = a0.Publisher(a0_file)
    for i in range(10):
        pkt = a0.Packet(f"{i}")
        pub.pub(pkt)
    pub = None
    a0_file = None
    a0_file_options = a0.File.Options.DEFAULT
    a0_file_options.open_options.readonly = True
    a0_file = a0.File(fp, a0_file_options)
    sub = a0.SubscriberSync(a0_file, a0.INIT_OLDEST, a0.ITER_NEXT)
    n = 0
    while sub.has_next():
        n += 1
        sub.next()
    print(f"n = {n}")
def main():
    test_fn()
    test_fn()
    test_fn()
```
The result of running this is
```
n = 10
n = 0
n = 0
```
when it should be 
```
n = 10
n = 10
n = 10
```
Note that while here I call `test_fn()` 3 times in a row, I have also tested calling it many more times, and only the first call ever report `n` to be non-zero. I've also tried increasing the size/number of packets written to significantly higher values (10s of millions) and that didn't change anything. I've examined the files written to with an external program, and all but the first are always filled with 0s.

The only way to make this work is to use python's multiprocessing library and make each call to `test_fn()` be in a separate process. If you do that, then it prints `n = 10` for every call to `test_fn()`.

**Comment by alephzero** [comment]
```py
a0_file_options = a0.File.Options.DEFAULT
a0_file_options.open_options.readonly = True
```
Since `a0_file_options` is a reference to `a0.File.Options.DEFAULT`, changes modify `DEFAULT` globally.
Discussed offline, we'll try to get a fix to make `DEFAULT` a function that returns a copy.
```py
a0_file_options = a0.File.Options.DEFAULT()
a0_file_options.open_options.readonly = True
```

**Comment by cschenck** [comment]
Pr #26 does this. When that merges we can close this issue.

**Comment by alephzero** [comment]
Solved by https://github.com/alephzero/py/pull/27
