### ISSUE TITLE
Permission Denied on Linux Ubuntu 20.04

### ISSUE THREAD

**Issue by soumith** [alephzero/py#47]
Ran this simple program:

```
import a0
import time

i = 0
p = a0.Publisher("some/topic")

while True:
    p.pub(f"{i=}")
    i += 1
    time.sleep(1)
```

It exited with the stdout `Permission Denied`.

Runs successfully under `root` user.

**Comment by alephzero** [comment]
I'm guessing the file `/dev/shm/alephzero/some/topic` is owned by root. You may have to either chown that file, or remove it and make sure it's created by a process running as you (or at least not root).

**Comment by soumith** [comment]
that fixed it, though it's not clear to my why that happened in the first place.
